### Create teacher
POST http://localhost:8080/auth/create-teacher
Content-Type: application/json

{
  "firstName": "Hans'",
  "lastName": "Wurst",
  "birthdate": "1992-07-29",
  "profile": {
    "userName": "wursti",
    "password": "1234",
    "email": "hans@wudrst.at",
    "active": true,
    "description": "hasdlft"
  }
}

### Create Student
POST http://localhost:8080/auth/create-student
Content-Type: application/json

{
  "firstName": "Schüler'",
  "lastName": "Hansi",
  "birthdate": "1992-04-25",
  "profile": {
    "userName": "hansl",
    "password": "12345",
    "email": "hans@hansi.at",
    "active": true
  }
}

### Get AuthToken via Email and Password of User
POST http://localhost:8080/auth
Content-Type: application/json

{
  "email": "hans@wurst.at",
  "password": "1234"

}

### Find all Teachers
GET http://localhost:8080/teacher

### Find User by Id
GET http://localhost:8080/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIxLCJzdWIiOiJoYW5zQHd1ZHJzdC5hdCIsImlhdCI6MTY4NzU5OTU2MywiZXhwIjoxNjg3NjAxMDAzfQ.R5SBhF--GczU4EZCqPT6aWdbEXxj1G_iTCDQtmtfys0



### Create conversation between two users
POST http://localhost:8080/conversation/create-conversation/22/21
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIyLCJzdWIiOiJoYW5zQGhhbnNpLmF0IiwiaWF0IjoxNjg4MTk5OTAwLCJleHAiOjE2ODgyMDEzNDB9.MOMxx5AQQUl5MWcRIPSU3MoGfZ3YG6_kq_8qgD3HPVo


### Send a message in a conversation
POST http://localhost:8080/message/send-message/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIyLCJzdWIiOiJoYW5zQGhhbnNpLmF0IiwiaWF0IjoxNjg4MTk5NTM2LCJleHAiOjE2ODgyMDA5NzZ9._wxaZESCEOk76JHehjIkiZeH9wbgl8Zo66vyEWpCgOc
{
  "title": "Neue Nachricht",
  "content": "erste nachricht",
  "senderId": 22
}

### Send appointment
POST http://localhost:8080/message/sendAppointment/4/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIyLCJzdWIiOiJoYW5zQGhhbnNpLmF0IiwiaWF0IjoxNjg4MTk5OTAwLCJleHAiOjE2ODgyMDEzNDB9.MOMxx5AQQUl5MWcRIPSU3MoGfZ3YG6_kq_8qgD3HPVo

{
  "title": "Neue Nachricht",
  "content": "erste nachricht",
  "studentId": 22
}

### Get Appointments
POST http://localhost:8080/appointment/get-appointments/22
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIyLCJzdWIiOiJoYW5zQGhhbnNpLmF0IiwiaWF0IjoxNjg4MTk5OTAwLCJleHAiOjE2ODgyMDEzNDB9.MOMxx5AQQUl5MWcRIPSU3MoGfZ3YG6_kq_8qgD3HPVo


### Send appointment in conversation
POST http://localhost:8080/app

### Create coaachings which are offered by a teacher
POST http://localhost:8080/coaching/offer-coaching/21
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIxLCJzdWIiOiJoYW5zQHd1ZHJzdC5hdCIsImlhdCI6MTY4ODE5OTg3MywiZXhwIjoxNjg4MjAxMzEzfQ.8tr3WeHZDCsF9yUvuBCpBXkn9LJfMRb8l_Sa-dMtfUc

{
  "coachings": [
    {
      "subject": "MATHEMATIK",
      "level": "Oberstufe",
      "rate": 20.5,
      "active": true
    }
  ]
}

### Update Teacher districts
PUT http://localhost:8080/teacher/updateDistricts/1
Content-Type: application/json

{
  "districts": ["DISTRICT_1010", "DISTRICT_1030"]
}

### Get Auth via token
POST http://localhost:8080/auth/info
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjExLCJzdWIiOiJzdHVkZW50MDFAZXhhbXBsZS5jb20iLCJpYXQiOjE2ODc2MDAyMTYsImV4cCI6MTY4NzYwMTY1Nn0.ROWaxwoTEEk_a8Fz770vNRhd4x0TnqWRfIw5xCw0DrA


### Confirm Appointments
PUT http://localhost:8080/appointment/confirm/1/21
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIxLCJzdWIiOiJoYW5zQHd1ZHJzdC5hdCIsImlhdCI6MTY4ODE5OTg3MywiZXhwIjoxNjg4MjAxMzEzfQ.8tr3WeHZDCsF9yUvuBCpBXkn9LJfMRb8l_Sa-dMtfUc