### Create Profile
POST http://localhost:8080/user/createProfile
Content-Type: application/json

{
  "userName": "dokoe92",
  "password": "1234",
  "email": "dokoe92@gmail.com",
  "description": "looking for some math coaching"
}


### Create Student
POST http://localhost:8080/user/createStudent
Content-Type: application/json

{
  "firstName": "Dominik",
  "lastName": "Köberl"
}

### Connect Profile with User
PUT http://localhost:8080/user/connect/3/1
Content-Type: application/json


### Create teacher
POST http://localhost:8080/user/createTeacher
Content-Type: application/json

{
  "firstName": "Hans'",
  "lastName": "Wurst",
  "birthdate": "1992-07-29",
  "profile": {
    "userName": "wursti",
    "password": "1234",
    "email": "hans@wurst.at",
    "active": true,
    "description": "hasdlft"
  }
}

### Find all Teachers
GET http://localhost:8080/teacher

